{% set version = "4.1.1" %}

package:
  name: jupyter-server-proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-proxy/jupyter_server_proxy-{{ version }}.tar.gz
  sha256: b9c6a945b10fa5373c1caa3f6481ce334b1bbe8946b48c8cb9f97097e26a8512

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv . --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.8.3
    - hatchling >=1.18.0
    - jupyterlab >=4.0.6,<5.0.0a0
    - pip
    - python >=3.8
  run:
    - aiohttp
    # importlib_metadata is only really needed with Python <3.10, but we've
    # failed to specify it to only be required then
    - importlib_metadata >=4.8.3
    - jupyter_server >=1.0
    - simpervisor >=1.0
    - tornado >=5.1
    - traitlets >=4.2.1
    - python >=3.8

test:
  requires:
    - jupyterlab >=4.0.6,<5.0.0a0
    - m2-grep  # [win]
    - pip
  commands:
    - pip check
    # print everything
    - pip list
    - jupyter labextension list
    - jupyter server extension list
    # output each
    - pip list 1>pip_list 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    - jupyter labextension list 1>labextensions 2>&1
    # check each
    - grep -iE "jupyter_server_proxy\s*{{ version.replace(".", "\\.") }}"                 pip_list
    - grep -iE "jupyter_server_proxy.*OK"                                                 server_extensions
    - grep -iE "@jupyterhub/jupyter-server-proxy.*{{ version.replace(".", "\\.") }}.*OK"  labextensions
  imports:
    - jupyter_server_proxy

about:
  home: https://github.com/jupyterhub/jupyter-server-proxy
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_server_proxy/labextension/static/third-party-licenses.json
  summary: Jupyter server extension to supervise and proxy web services
  description: |
    Jupyter Server Proxy lets you run arbitrary external processes (such as
    RStudio, Shiny Server, syncthing, PostgreSQL, etc) alongside your notebook,
    and provide authenticated web access to them.
  doc_url: https://jupyter-server-proxy.readthedocs.io
  dev_url: https://github.com/jupyterhub/jupyter-server-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
    - xhochy
    - consideratio
    - bollwyvl
